### ISSUE TITLE
Not able to add comments on existing issues

### ISSUE THREAD

**Issue by neozenweb** [Cynthesize/cynthesize-frontend#113] opened 2019-02-12 17:57 UTC
**Description** : I am working on another issue, and to test the issue I have to add new comments. But I could only type in the comment but no buttons or scroll bar to add the comment.

**Browser** :Chrome
**Steps to reproduce the issue** 
1. Go on to the user profile page by clicking on the top right hand corner user icon.
2. Click on one of the existing projects on the profile (which has checkpoints or you can create these by using "Add Issue").
3. On the Left hand side click on one of the checkpoints.
4. On the main panel click on the comment icon.

![nopagescrollcomments](https://user-images.githubusercontent.com/37545009/52651051-7ba8d380-2eb9-11e9-8e24-196e1565bb7d.jpg)

**Comment by WickedBrat** [comment] 2019-02-12 20:07
@neozenweb Please add the steps to reproduce

**Comment by neozenweb** [comment] 2019-02-12 20:30
Edited the original to add the steps to reproduce this issue.

**Comment by WickedBrat** [comment] 2019-02-13 13:31
@neozenweb Does the scrolling not work? I'm unable to reproduce the error.

**Comment by neozenweb** [comment] 2019-02-13 13:36
Yes the scrolling does not work and I am not able to add the comment. I checked the same error on the netlify development version too. I am using Chrome browser.

**Comment by WickedBrat** [comment] 2019-02-13 20:52
@neozenweb It appears to work fine with me.

![peek 2019-02-14 02-21](https://user-images.githubusercontent.com/45864807/52743087-44dcd580-2fff-11e9-81c1-c8a7985d91b7.gif)

@prijeshb @sanyamdogra @zerefwayne Can you please confirm this?

**Comment by prijeshb** [comment] 2019-02-14 08:27
@WickedBrat  Yes he is right about the scrolling issue of comment section. There seems to have problem in each of those places where editor is used.
**Screenshot**:
 No scroll bar is loaded in editor


![ezgif com-crop 1](https://user-images.githubusercontent.com/16492616/52772933-c49a8c80-305f-11e9-9d5c-e18dd3733e11.gif)

**Comment by WickedBrat** [comment] 2019-02-14 09:27
@prijeshb I suppose this is a different issue, right @neozenweb? 
Also, @prijeshb This issue can be easily solved by removing the CSS applied on the `.CodeMirror` in the file [comments.component.scss](https://github.com/Cynthesize/cynthesize-frontend/blob/master/src/app/shared/comments/comments.component.scss)

**Comment by sanyamdogra** [comment] 2019-02-14 10:52
![image](https://user-images.githubusercontent.com/33497630/52782194-80fe4d80-3074-11e9-87ce-88df8062f338.png)
@WickedBrat i am able to add comments and  i don't think there's an issue with it. As @prijeshb mentioned there's an issue with scroll in td text editor.

**Comment by prijeshb** [comment] 2019-02-14 11:04
@WickedBrat  yes there is no problem with posting comments but is there with scrolling.

**Comment by WickedBrat** [comment] 2019-02-14 13:48
@prijeshb Please open an issue for the size issue of the CodeEditor and the CSS related to it. 

@neozenweb I think this issue could be solved by adding a scrollbar in the verticle direction. Would you like to solve this?

**Comment by sanyamdogra** [comment] 2019-02-18 02:28
Why is this issue open? Please close it @neozenweb

**Closed** 2019-04-27 14:51 UTC
Labels: requires-confirmation
